#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=30

start(){
  enable=$(uci get sfe.config.enabled 2>/dev/null)
  wifi=$(uci get sfe.config.wifi)
	if [ $enable -eq 1 ]; then
      echo "enable"
      ! (lsmod | grep fast_classifier >/dev/null) && (modprobe fast_classifier)
      if [ $wifi -eq 1 ] ;  then
       echo "wifi"
       echo 1 > /sys/fast_classifier/skip_to_bridge_ingress
      else
       echo "no wifi"
       echo 0 > /sys/fast_classifier/skip_to_bridge_ingress
      fi
   else
      rmmod fast_classifier
      echo "stop"
  fi
}

stop(){
    enable=$(uci get sfe.config.enabled 2>/dev/null)
	  [ $enable -ne 1 ] && rmmod fast_classifier
	  echo "stop"
}

restart(){
	  stop
	  start
}


